[[targets]]
name = "Ryzen 5 5500"
category = "cpu"
max_price = 600.00
search_terms = [
  "ryzen 5 5500",
  "amd ryzen 5 5500",
]

[[targets]]
name = "Placa Mae B450M/A520M"
category = "motherboard"
max_price = 450.00
search_terms = [
  "b450m",
  "a520m",
  "placa mae b450",
  "placa mae a520",
  "placa mae b450m",
]

[[targets]]
name = "GTX 750 Ti 4GB"
category = "gpu"
max_price = 700.00
search_terms = [
  "gtx 750 ti",
  "geforce gtx 750 ti",
  "nvidia gtx 750 ti",
  "gtx 750 ti 4gb",
]

[[targets]]
name = "Memoria DDR4 8GB 3200MHz"
category = "ram"
max_price = 400.00
search_terms = [
  "memoria ddr4 8gb 3200",
  "ddr4 8gb 3200mhz",
  "pente 8gb ddr4",
  "memoria ram 8gb 3200",
  "8gb ddr4 3200mhz",
]

[[targets]]
name = "SSD 480GB"
category = "ssd"
max_price = 450.00
search_terms = [
  "ssd 480gb",
  "ssd 480",
  "ssd 512gb",
  "ssd 480gb sata",
]
